#!/usr/bin/env bash
# Displays the time for 12 hrs 59 min

i=0
while [ $i -le 12 ]
do
    echo "Hour: $i"
    min=1
    while [ $min -lt 60 ]
    do
        echo "$min"
        ((min++))
    done
    ((i++))
done
